name: Generate on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run generators.py
        run: python generators.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-action@codenight.et"
          git checkout -b ${{ github.head_ref }}
          git add README.md
          echo "Generated files for ${{ github.event.pull_request.title }}"
          git commit -m "Generated files for ${{ github.event.pull_request.title }}"
          echo "Pushing to ${{ github.event.pull_request.head.ref }}"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
          echo "Successfully pushed to ${{ github.event.pull_request.head.ref }}"
